version : "3"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - ./.env

#   mongo:
#     image: mongo
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=moshe
#       - MONGO_INITDB_ROOT_PASSWORD=123
#     volumes:
#       - mongo-db:/data/db


# volumes:
#   mongo-db: